require: rubocop-rspec

AllCops:
  Exclude:
    - "lib/test_boosters/rspec_booster.rb"
    - "lib/test_boosters/cucumber_booster.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/CollectionMethods:
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size"
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/PercentLiteralDelimiters:
  Enabled: false
