require: rubocop-rspec

AllCops:
  DisplayCopNames: true

  Exclude:
    - "vendor/**/*"
    - "lib/test_boosters/rspec_booster.rb"
    - "lib/test_boosters/cucumber_booster.rb"
    - "lib/test_boosters/insights_uploader.rb"
    - "test_data_pass/**/*"
    - "test_data_fail/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/CollectionMethods:
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size"
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/PercentLiteralDelimiters:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Style/EmptyLinesAroundBlockBody:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
