require: rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/CollectionMethods:
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size"
  Enabled: true

Metrics/LineLength:
  Max: 120
