default: --format pretty  --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
semaphoreci: --format json --out=../cucumber_report.json
