default: --format pretty --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci --profile semaphoreci
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
semaphoreci: --format json --out=/tmp/cucumber_report.json
